version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: chat_app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"

